version: "3.7"
services:
  docker_model:
    build: $PWD/containers/default
    container_name: docker_model_default
    working_dir: /app
    volumes:
      - $PWD/containers/default/volume:/app
    ##You can set environment variables here!
    # environment: 
    #   - ENV_VAR_NAME: ENV_VAR_VALUE  
    ##Is possible to open ports too (EXTERNAL : INTERNAL)
    # ports: 
    #   - 8000:80
    ##If you need, this container will only start after another container gets up.
    # depends_on: 
    #   - SERVICE_NAME
    ##By default, a default network will be created, use the same network with other containers to have comunication between them
    networks: 
      - default

networks:
  default:
    external:
      name: docker_model