services:
  prosody:
    container_name: prosody
    build: ./containers/prosody
    working_dir: /app
    volumes:
      - ./containers/prosody/volume:/app
    networks: 
      - prosody

networks:
  prosody:
      name: prosody
      external: true
