services:
  docker_model:
    build: $PWD/containers/prosody
    container_name: prosody
    working_dir: /app
    volumes:
      - $PWD/containers/prosody/volume:/app
    ##You can set environment variables here!
    # environment: 
    #   - ENV_VAR_NAME=ENV_VAR_VALUE  
    ##Is possible to open ports too (EXTERNAL : INTERNAL)
    # ports: 
    #   - 5222:5222
    ##If you need, this container will only start after another container gets up.
    # depends_on: 
    #   - SERVICE_NAME
    ##By default, a default network will be created, use the same network with other containers to have comunication between them
    networks: 
      - prosody

networks:
  prosody:
      name: prosody
      external: true